增加功能
Jinxuyang/sust-navigation pull request #1
Opened 2021-05-13 12:25 UTC by whirabbit

2021-05-13 13:12 UTC, Jinxuyang requested changes

2021-05-13 13:12 UTC, Jinxuyang commented on cloudfunctions/people-unit-point/index.js
> +  for(var i=0;i<length;i++){
使用let代替var

2021-05-13 13:12 UTC, Jinxuyang commented on cloudfunctions/people-unit-point/index.js
> +}
注意缩进

2021-05-13 13:12 UTC, Jinxuyang commented on cloudfunctions/point/index.js
> +  cloud.init()
cloud.init() 应在该函数外

2021-05-13 13:12 UTC, Jinxuyang commented on cloudfunctions/units-point/index.js
> +}
注意缩进

2021-05-13 13:12 UTC, Jinxuyang commented on cloudfunctions/units-point/index.js
> +if (floor!=null) {
此处为null还是undefined测试过吗

2021-05-15 11:54 UTC, whirabbit commented
格式化了文档,修复了调用doc方法时_id可能不存在的问题,_id不存在时返回null

2021-05-15 13:22 UTC, merged